name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create and Build Android App
        run: |
          cordova create buildApp com.remote.app RemoteApp
          cd buildApp
          cordova platform add android
          rm -rf www/*
          cp ../index.html www/index.html
          cordova build android --no-telemetry

      - name: Save APK File
        uses: actions/upload-artifact@v4
        with:
          name: TargetMobileApp
          path: buildApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
